/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutPoliciesRouteImport } from './routes/about/policies'
import { Route as AcademicsFacultyRouteImport } from './routes/academics/faculty'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions/index'
import { Route as AdmissionsFormRouteImport } from './routes/admissions/form'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as InfrastructureIndexRouteImport } from './routes/infrastructure/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NoticeBoardIndexRouteImport } from './routes/notice-board/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as SchoolInfoIndexRouteImport } from './routes/school-info/index'
import { Route as SchoolInfoCircularsRouteImport } from './routes/school-info/circulars'
import { Route as SchoolInfoFeeStructureRouteImport } from './routes/school-info/fee-structure'
import { Route as SchoolInfoMandatoryDisclosureRouteImport } from './routes/school-info/mandatory-disclosure'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPoliciesRoute = AboutPoliciesRouteImport.update({
  id: '/about/policies',
  path: '/about/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsFacultyRoute = AcademicsFacultyRouteImport.update({
  id: '/academics/faculty',
  path: '/academics/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsFormRoute = AdmissionsFormRouteImport.update({
  id: '/admissions/form',
  path: '/admissions/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureIndexRoute = InfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeBoardIndexRoute = NoticeBoardIndexRouteImport.update({
  id: '/notice-board/',
  path: '/notice-board/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolInfoIndexRoute = SchoolInfoIndexRouteImport.update({
  id: '/school-info/',
  path: '/school-info/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolInfoCircularsRoute = SchoolInfoCircularsRouteImport.update({
  id: '/school-info/circulars',
  path: '/school-info/circulars',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolInfoFeeStructureRoute = SchoolInfoFeeStructureRouteImport.update({
  id: '/school-info/fee-structure',
  path: '/school-info/fee-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolInfoMandatoryDisclosureRoute =
  SchoolInfoMandatoryDisclosureRouteImport.update({
    id: '/school-info/mandatory-disclosure',
    path: '/school-info/mandatory-disclosure',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/policies': typeof AboutPoliciesRoute
  '/academics/faculty': typeof AcademicsFacultyRoute
  '/admissions/form': typeof AdmissionsFormRoute
  '/school-info/circulars': typeof SchoolInfoCircularsRoute
  '/school-info/fee-structure': typeof SchoolInfoFeeStructureRoute
  '/school-info/mandatory-disclosure': typeof SchoolInfoMandatoryDisclosureRoute
  '/about/': typeof AboutIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/events/': typeof EventsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/news/': typeof NewsIndexRoute
  '/notice-board/': typeof NoticeBoardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/school-info/': typeof SchoolInfoIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/policies': typeof AboutPoliciesRoute
  '/academics/faculty': typeof AcademicsFacultyRoute
  '/admissions/form': typeof AdmissionsFormRoute
  '/school-info/circulars': typeof SchoolInfoCircularsRoute
  '/school-info/fee-structure': typeof SchoolInfoFeeStructureRoute
  '/school-info/mandatory-disclosure': typeof SchoolInfoMandatoryDisclosureRoute
  '/about': typeof AboutIndexRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/events': typeof EventsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/infrastructure': typeof InfrastructureIndexRoute
  '/news': typeof NewsIndexRoute
  '/notice-board': typeof NoticeBoardIndexRoute
  '/portal': typeof PortalIndexRoute
  '/school-info': typeof SchoolInfoIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about/policies': typeof AboutPoliciesRoute
  '/academics/faculty': typeof AcademicsFacultyRoute
  '/admissions/form': typeof AdmissionsFormRoute
  '/school-info/circulars': typeof SchoolInfoCircularsRoute
  '/school-info/fee-structure': typeof SchoolInfoFeeStructureRoute
  '/school-info/mandatory-disclosure': typeof SchoolInfoMandatoryDisclosureRoute
  '/about/': typeof AboutIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/events/': typeof EventsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/news/': typeof NewsIndexRoute
  '/notice-board/': typeof NoticeBoardIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/school-info/': typeof SchoolInfoIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/policies'
    | '/academics/faculty'
    | '/admissions/form'
    | '/school-info/circulars'
    | '/school-info/fee-structure'
    | '/school-info/mandatory-disclosure'
    | '/about/'
    | '/admissions/'
    | '/contact/'
    | '/events/'
    | '/gallery/'
    | '/infrastructure/'
    | '/news/'
    | '/notice-board/'
    | '/portal/'
    | '/school-info/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/policies'
    | '/academics/faculty'
    | '/admissions/form'
    | '/school-info/circulars'
    | '/school-info/fee-structure'
    | '/school-info/mandatory-disclosure'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/infrastructure'
    | '/news'
    | '/notice-board'
    | '/portal'
    | '/school-info'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about/policies'
    | '/academics/faculty'
    | '/admissions/form'
    | '/school-info/circulars'
    | '/school-info/fee-structure'
    | '/school-info/mandatory-disclosure'
    | '/about/'
    | '/admissions/'
    | '/contact/'
    | '/events/'
    | '/gallery/'
    | '/infrastructure/'
    | '/news/'
    | '/notice-board/'
    | '/portal/'
    | '/school-info/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutPoliciesRoute: typeof AboutPoliciesRoute
  AcademicsFacultyRoute: typeof AcademicsFacultyRoute
  AdmissionsFormRoute: typeof AdmissionsFormRoute
  SchoolInfoCircularsRoute: typeof SchoolInfoCircularsRoute
  SchoolInfoFeeStructureRoute: typeof SchoolInfoFeeStructureRoute
  SchoolInfoMandatoryDisclosureRoute: typeof SchoolInfoMandatoryDisclosureRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  InfrastructureIndexRoute: typeof InfrastructureIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NoticeBoardIndexRoute: typeof NoticeBoardIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  SchoolInfoIndexRoute: typeof SchoolInfoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/policies': {
      id: '/about/policies'
      path: '/about/policies'
      fullPath: '/about/policies'
      preLoaderRoute: typeof AboutPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/faculty': {
      id: '/academics/faculty'
      path: '/academics/faculty'
      fullPath: '/academics/faculty'
      preLoaderRoute: typeof AcademicsFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/form': {
      id: '/admissions/form'
      path: '/admissions/form'
      fullPath: '/admissions/form'
      preLoaderRoute: typeof AdmissionsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/': {
      id: '/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof InfrastructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-board/': {
      id: '/notice-board/'
      path: '/notice-board'
      fullPath: '/notice-board/'
      preLoaderRoute: typeof NoticeBoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-info/': {
      id: '/school-info/'
      path: '/school-info'
      fullPath: '/school-info/'
      preLoaderRoute: typeof SchoolInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-info/circulars': {
      id: '/school-info/circulars'
      path: '/school-info/circulars'
      fullPath: '/school-info/circulars'
      preLoaderRoute: typeof SchoolInfoCircularsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-info/fee-structure': {
      id: '/school-info/fee-structure'
      path: '/school-info/fee-structure'
      fullPath: '/school-info/fee-structure'
      preLoaderRoute: typeof SchoolInfoFeeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-info/mandatory-disclosure': {
      id: '/school-info/mandatory-disclosure'
      path: '/school-info/mandatory-disclosure'
      fullPath: '/school-info/mandatory-disclosure'
      preLoaderRoute: typeof SchoolInfoMandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutPoliciesRoute: AboutPoliciesRoute,
  AcademicsFacultyRoute: AcademicsFacultyRoute,
  AdmissionsFormRoute: AdmissionsFormRoute,
  SchoolInfoCircularsRoute: SchoolInfoCircularsRoute,
  SchoolInfoFeeStructureRoute: SchoolInfoFeeStructureRoute,
  SchoolInfoMandatoryDisclosureRoute: SchoolInfoMandatoryDisclosureRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  InfrastructureIndexRoute: InfrastructureIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  NoticeBoardIndexRoute: NoticeBoardIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  SchoolInfoIndexRoute: SchoolInfoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
